### ISSUE TITLE
ymcd服务启动错误

### ISSUE THREAD

**Issue by kun945** [snakeleon/YouCompleteMe-x64#8]
VIM版本：8.2 64bit
PYTHON版本：3.10.2 64bit
错误日志：
···
2022-05-06 14:43:26,785 - ERROR - DLL load failed while importing ycm_core: 找不到指定的模块。
Traceback (most recent call last):
  File "C:\Program Files\Vim\vimfiles\bundle\YouCompleteMe\third_party\ycmd\ycmd\utils.py", line 502, in ImportAndCheckCore
    ycm_core = ImportCore()
  File "C:\Program Files\Vim\vimfiles\bundle\YouCompleteMe\third_party\ycmd\ycmd\utils.py", line 493, in ImportCore
    import ycm_core as ycm_core
ImportError: DLL load failed while importing ycm_core: 找不到指定的模块。

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Program Files\Vim\vimfiles\bundle\YouCompleteMe\third_party\ycmd\ycmd\utils.py", line 505, in ImportAndCheckCore
    ycm_core = ImportCore()
  File "C:\Program Files\Vim\vimfiles\bundle\YouCompleteMe\third_party\ycmd\ycmd\utils.py", line 493, in ImportCore
    import ycm_core as ycm_core
ImportError: DLL load failed while importing ycm_core: 找不到指定的模块。 
···

**Comment by kun945** [comment]
已解决，是权限问题。
第一次运行需要插件目录的可写权限，否则ycmd服务会启动失败。建议第一运行使用管理员权限，后面默认用户权限就可以了。
